name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:


jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: openbread
          POSTGRES_USER: openbread
          POSTGRES_PASSWORD: openbread
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U openbread"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('openbread-backend/openbread/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: openbread-frontend/package-lock.json

      - name: Backend - Gradle wrapper permissions
        run: chmod +x ./openbread-backend/openbread/gradlew

      - name: Frontend - install
        working-directory: openbread-frontend
        run: npm ci

      - name: Frontend - build
        working-directory: openbread-frontend
        run: npm run build

      - name: Mover frontend a recursos estaticos de Backend
        run: |
          mkdir -p openbread-backend/openbread/src/main/resources/static
          cp -r openbread-frontend/dist/* openbread-backend/openbread/src/main/resources/static/

      - name: Backend - test
        working-directory: openbread-backend/openbread
        env:
            DB_URL: jdbc:postgresql://localhost:5432/openbread
            DB_USERNAME: openbread
            DB_PASSWORD: openbread
        run: ./gradlew test

      - name: Backend - build
        working-directory: openbread-backend/openbread
        run: ./gradlew build -x test

      - name: Iniciar sesión Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convertir repositorio a minúsculas
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: repo-string
        run: |
          echo "REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Construir Docker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
         context: ./openbread-backend/openbread
         file: ./openbread-backend/openbread/Dockerfile
         push: true
         tags: ghcr.io/${{ env.REPO_LOWER }}/openbread-backend:latest
